"""add_invitations_table

Revision ID: 134ace9e077b
Revises: 4915f7e12ad9
Create Date: 2025-10-27 18:03:44.862502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134ace9e077b'
down_revision = '4915f7e12ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'expired', 'cancelled')", name='valid_status'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'invited_email', 'status', name='unique_active_invitation')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_invited_email'), ['invited_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_invited_user_id'), ['invited_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_team_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_invitations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_invitations_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_invited_user_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_invited_email'))
        batch_op.drop_index(batch_op.f('ix_invitations_expires_at'))

    op.drop_table('invitations')
    # ### end Alembic commands ###
