"""add file_reference_details to ai_chats

Revision ID: 26885c481157
Revises: 2f2d1017ba16
Create Date: 2025-10-20 14:06:58.431833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26885c481157'
down_revision = '2f2d1017ba16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_reference_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_column('file_reference_details')

    # ### end Alembic commands ###
