"""Add file_references to AIChat model

Revision ID: 2f2d1017ba16
Revises: 4874aa66d2c0
Create Date: 2025-10-18 22:46:27.190669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2d1017ba16'
down_revision = '4874aa66d2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_references', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_column('file_references')

    # ### end Alembic commands ###
