"""add has_used_trial to teams

Revision ID: 330fa9731a9d
Revises: 939ba99f4c5c
Create Date: 2025-11-10 14:45:06.086495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330fa9731a9d'
down_revision = '939ba99f4c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_trial', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.create_index(batch_op.f('ix_teams_has_used_trial'), ['has_used_trial'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_has_used_trial'))
        batch_op.drop_column('has_used_trial')

    # ### end Alembic commands ###
