"""Add cascade delete constraints to foreign keys

Revision ID: 4874aa66d2c0
Revises: 78c9a87636b2
Create Date: 2025-10-17 18:39:48.922251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4874aa66d2c0'
down_revision = '78c9a87636b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_chats_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chats_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chats_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_chats_chat_id_fkey'), 'chats', ['chat_id'], ['id'])

    # ### end Alembic commands ###
