"""Add projects table with name and description fields

Revision ID: 6ea1bc23c187
Revises: b2d13e357363
Create Date: 2025-10-15 13:47:02.187760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea1bc23c187'
down_revision = 'b2d13e357363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('old_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audit_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('audit_metadata')
        batch_op.drop_column('error_message')
        batch_op.drop_column('success')
        batch_op.drop_column('session_id')
        batch_op.drop_column('new_values')
        batch_op.drop_column('old_values')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('action_type')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_is_deleted'))

    op.drop_table('projects')
    # ### end Alembic commands ###
