"""Add chat_name field to AIChat model

Revision ID: 78c9a87636b2
Revises: fe4f42804624
Create Date: 2025-10-17 15:13:41.874254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9a87636b2'
down_revision = 'fe4f42804624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_column('chat_name')

    # ### end Alembic commands ###
