"""change_referenced_chat_id_to_referenced_chat_ids_json

Revision ID: 82cd8fb77371
Revises: 1c91ddf70fe0
Create Date: 2025-11-20 19:33:50.854231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cd8fb77371'
down_revision = '1c91ddf70fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import json
    from sqlalchemy import text, inspect as sa_inspect
    
    # Step 1: Add new JSON column (nullable initially)
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_chat_ids', sa.JSON(), nullable=True))
    
    # Step 2: Migrate existing data: convert referenced_chat_id to [referenced_chat_id] format
    connection = op.get_bind()
    # Get all rows with referenced_chat_id
    result = connection.execute(text("SELECT id, referenced_chat_id FROM ai_chats WHERE referenced_chat_id IS NOT NULL"))
    rows = result.fetchall()
    
    # Update each row: convert single ID to JSON array format
    for row in rows:
        ai_chat_id, referenced_chat_id = row
        # Convert to JSON array format
        json_array = json.dumps([referenced_chat_id])
        connection.execute(
            text("UPDATE ai_chats SET referenced_chat_ids = :json_array WHERE id = :ai_chat_id"),
            {"json_array": json_array, "ai_chat_id": ai_chat_id}
        )
    
    # Step 3: Drop old column and foreign key constraint
    # Find and drop constraints/indexes before dropping column
    connection = op.get_bind()
    inspector = sa_inspect(connection)
    
    # Find and drop foreign key constraint
    foreign_keys = inspector.get_foreign_keys('ai_chats')
    for fk in foreign_keys:
        if 'referenced_chat_id' in fk.get('constrained_columns', []):
            constraint_name = fk.get('name')
            if constraint_name:
                try:
                    op.drop_constraint(constraint_name, 'ai_chats', type_='foreignkey')
                except Exception:
                    pass  # Constraint might not exist or have different name
    
    # Find and drop index
    indexes = inspector.get_indexes('ai_chats')
    for index in indexes:
        if 'referenced_chat_id' in index.get('column_names', []):
            index_name = index.get('name')
            if index_name:
                try:
                    op.drop_index(index_name, 'ai_chats')
                except Exception:
                    pass  # Index might not exist
    
    # Finally, drop the column using batch_alter_table
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_column('referenced_chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import json
    from sqlalchemy import text
    
    # Step 1: Add back old integer column
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_chat_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_ai_chats_referenced_chat_id', ['referenced_chat_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_chats_referenced_chat_id', 'chats', ['referenced_chat_id'], ['id'])
    
    # Step 2: Migrate data back: take first ID from JSON array
    connection = op.get_bind()
    result = connection.execute(text("SELECT id, referenced_chat_ids FROM ai_chats WHERE referenced_chat_ids IS NOT NULL"))
    rows = result.fetchall()
    
    for row in rows:
        ai_chat_id, referenced_chat_ids_json = row
        if referenced_chat_ids_json:
            try:
                ids_list = json.loads(referenced_chat_ids_json) if isinstance(referenced_chat_ids_json, str) else referenced_chat_ids_json
                if ids_list and len(ids_list) > 0:
                    # Take first ID from array
                    first_id = ids_list[0]
                    connection.execute(
                        text("UPDATE ai_chats SET referenced_chat_id = :first_id WHERE id = :ai_chat_id"),
                        {"first_id": first_id, "ai_chat_id": ai_chat_id}
                    )
            except (json.JSONDecodeError, TypeError, IndexError):
                pass  # Skip invalid data
    
    # Step 3: Drop new JSON column
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_column('referenced_chat_ids')
    # ### end Alembic commands ###
