"""add_is_public_field_to_projects

Revision ID: 8e5d3b0578ae
Revises: 26885c481157
Create Date: 2025-10-27 16:55:54.837471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5d3b0578ae'
down_revision = '26885c481157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.create_index(batch_op.f('ix_projects_is_public'), ['is_public'], unique=False)
    
    # Remove the server default after adding the column
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('is_public', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_is_public'))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
