"""add_chat_references_table

Revision ID: a1b2c3d4e5f6
Revises: d2a12f31637b
Create Date: 2025-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'd2a12f31637b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenced_chat_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_model', sa.String(length=100), nullable=True),
    sa.Column('summary_tokens', sa.Integer(), nullable=True),
    sa.Column('referenced_chat_message_count', sa.Integer(), nullable=True),
    sa.Column('last_message_id_included', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_refreshed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referenced_chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_refreshed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referenced_chat_id', name='uq_chat_references_referenced_chat_id')
    )
    with op.batch_alter_table('chat_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_references_referenced_chat_id'), ['referenced_chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_references_referenced_chat_id'))

    op.drop_table('chat_references')
    # ### end Alembic commands ###

