"""add_referenced_chat_id_to_ai_chats

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-01-20 10:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_chat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ai_chats_referenced_chat_id', 'chats', ['referenced_chat_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_ai_chats_referenced_chat_id'), ['referenced_chat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chats_referenced_chat_id'))
        batch_op.drop_constraint('fk_ai_chats_referenced_chat_id', type_='foreignkey')
        batch_op.drop_column('referenced_chat_id')

    # ### end Alembic commands ###

