"""Initial migration

Revision ID: b2d13e357363
Revises: 
Create Date: 2025-10-14 15:51:56.432732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d13e357363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fontes_juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('passaporte', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('endereco_completo', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('renda_anual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('patrimonio_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('origem_patrimonio', sa.Text(), nullable=True),
    sa.Column('residente_fiscal_brasil', sa.Boolean(), nullable=True),
    sa.Column('residente_fiscal_eua', sa.Boolean(), nullable=True),
    sa.Column('outros_paises_residencia', sa.Text(), nullable=True),
    sa.Column('objetivos_planejamento', sa.Text(), nullable=True),
    sa.Column('tolerancia_risco', sa.String(length=20), nullable=True),
    sa.Column('horizonte_investimento', sa.String(length=50), nullable=True),
    sa.Column('possui_offshore', sa.Boolean(), nullable=True),
    sa.Column('detalhes_offshore', sa.Text(), nullable=True),
    sa.Column('possui_trust', sa.Boolean(), nullable=True),
    sa.Column('detalhes_trust', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['legal_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('jurisdicao', sa.String(length=50), nullable=True),
    sa.Column('estado_jurisdicao', sa.String(length=50), nullable=True),
    sa.Column('conteudo_template', sa.Text(), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('formato_saida', sa.String(length=10), nullable=True),
    sa.Column('requer_assinatura', sa.Boolean(), nullable=True),
    sa.Column('requer_notarizacao', sa.Boolean(), nullable=True),
    sa.Column('nivel_complexidade', sa.String(length=20), nullable=True),
    sa.Column('patrimonio_minimo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('patrimonio_maximo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_legal', sa.Text(), nullable=True),
    sa.Column('consideracoes_fiscais', sa.Text(), nullable=True),
    sa.Column('versao', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_gerados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_final', sa.Text(), nullable=False),
    sa.Column('dados_utilizados', sa.JSON(), nullable=True),
    sa.Column('parametros_geracao', sa.JSON(), nullable=True),
    sa.Column('formato_arquivo', sa.String(length=10), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('requer_revisao', sa.Boolean(), nullable=True),
    sa.Column('revisado_por', sa.Integer(), nullable=True),
    sa.Column('data_revisao', sa.DateTime(), nullable=True),
    sa.Column('requer_assinatura', sa.Boolean(), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('assinado_por', sa.String(length=200), nullable=True),
    sa.Column('requer_notarizacao', sa.Boolean(), nullable=True),
    sa.Column('notarizado', sa.Boolean(), nullable=True),
    sa.Column('data_notarizacao', sa.DateTime(), nullable=True),
    sa.Column('notario_info', sa.JSON(), nullable=True),
    sa.Column('data_validade', sa.DateTime(), nullable=True),
    sa.Column('jurisdicao_aplicavel', sa.String(length=50), nullable=True),
    sa.Column('compliance_verificado', sa.Boolean(), nullable=True),
    sa.Column('historico_alteracoes', sa.JSON(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_confidencial', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates_documento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_index')
    op.drop_table('documentos_gerados')
    op.drop_table('templates_documento')
    op.drop_table('scraped_content')
    op.drop_table('documentos_upload')
    op.drop_table('clientes')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('legal_sources')
    op.drop_table('fontes_juridicas')
    # ### end Alembic commands ###
