"""add_payment_plans_and_subscriptions

Revision ID: d2a12f31637b
Revises: 4fe04c9d960
Create Date: 2025-10-28 18:45:14.123594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a12f31637b'
down_revision = '4fe04c9d960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_plan_uuid', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=100), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_team_members_per_team', sa.Integer(), nullable=False),
    sa.Column('max_project_members_per_project', sa.Integer(), nullable=False),
    sa.Column('can_add_users_to_project', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('max_project_members_per_project >= -1', name='chk_pp_max_project_members_gte_neg1'),
    sa.CheckConstraint('max_projects >= -1', name='chk_pp_max_projects_gte_neg1'),
    sa.CheckConstraint('max_team_members_per_team >= 0', name='chk_pp_max_team_members_nonneg'),
    sa.CheckConstraint('max_teams >= 0', name='chk_pp_max_teams_nonneg'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plans_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_payment_plan_uuid'), ['payment_plan_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_plans_stripe_product_id'), ['stripe_product_id'], unique=False)

    op.create_table('plan_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_price_uuid', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('compare_at_cents', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('per_seat_amount_cents', sa.Integer(), nullable=True),
    sa.Column('per_seat_metric', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("interval IN ('month','year')", name='chk_price_interval'),
    sa.CheckConstraint('amount_cents >= 0', name='chk_price_amount_nonneg'),
    sa.CheckConstraint('compare_at_cents IS NULL OR compare_at_cents >= 0', name='chk_price_compare_at_nonneg'),
    sa.CheckConstraint('interval_count >= 1', name='chk_price_interval_count'),
    sa.CheckConstraint('per_seat_amount_cents IS NULL OR per_seat_amount_cents >= 0', name='chk_price_per_seat_nonneg'),
    sa.CheckConstraint('trial_days >= 0', name='chk_price_trial_days_nonneg'),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_prices_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_prices_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_plan_prices_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_prices_plan_price_uuid'), ['plan_price_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_plan_prices_stripe_price_id'), ['stripe_price_id'], unique=True)

    op.create_table('team_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_subscription_uuid', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('billing_user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_latest_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_promo_code_id', sa.String(length=100), nullable=True),
    sa.Column('discount_ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_consumed', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='chk_sub_quantity_pos'),
    sa.ForeignKeyConstraint(['billing_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['plan_prices.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_team_subscription_active', ['team_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_billing_user_id'), ['billing_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_team_subscription_uuid'), ['team_subscription_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_subscriptions_trial_end'), ['trial_end'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_trial_end'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_team_subscription_uuid'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_team_subscriptions_billing_user_id'))
        batch_op.drop_index('ix_team_subscription_active')

    op.drop_table('team_subscriptions')
    with op.batch_alter_table('plan_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_prices_stripe_price_id'))
        batch_op.drop_index(batch_op.f('ix_plan_prices_plan_price_uuid'))
        batch_op.drop_index(batch_op.f('ix_plan_prices_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_prices_key'))
        batch_op.drop_index(batch_op.f('ix_plan_prices_is_active'))

    op.drop_table('plan_prices')
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plans_stripe_product_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_payment_plan_uuid'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_is_active'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_code'))

    op.drop_table('payment_plans')
    # ### end Alembic commands ###
