"""Add AIChat and AIStats

Revision ID: fe4f42804624
Revises: bfa672eff114
Create Date: 2025-10-16 19:20:46.746507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4f42804624'
down_revision = 'bfa672eff114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('ai_answer', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('ai_model_provider', sa.String(length=50), nullable=False),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('conversation_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chats_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chats_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chats_user_id'), ['user_id'], unique=False)

    op.create_table('ai_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_chat_id', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('api_version', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('error_occurred', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_chat_id'], ['ai_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_stats_ai_chat_id'), ['ai_chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_stats_ai_chat_id'))

    op.drop_table('ai_stats')
    with op.batch_alter_table('ai_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_chats_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_ai_chats_chat_id'))

    op.drop_table('ai_chats')
    # ### end Alembic commands ###
